language: python
python:
  - 2.7
install:
  - pip install -r dev_requirements.txt
  - pip install -e .
script:
  - py.test -vvrs
  - flake8
notifications:
  irc:
    channels:
      - "chat.freenode.net#etherex-dev"
    use_notice: true
    skip_join: true